<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2015-07-15 12:26:54
 */
return [
    'all' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [
            'js/all-31f88aec214af315b38d90d7ae4d0d66.js',
        ],
        'css' => [
            'css/all-21bdc94f39bfdd14e9ee4fd491a4d5e4.css',
        ],
    ],
    'yii\\web\\JqueryAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'yii\\web\\YiiAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'all',
        ],
    ],
    'yii\\bootstrap\\BootstrapAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'uran1980\\yii\\assets\\jQueryEssential\\JqueryCookieAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'all',
        ],
    ],
    'uran1980\\yii\\assets\\jQueryEssential\\JqueryEasingAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'all',
        ],
    ],
    'uran1980\\yii\\assets\\jQueryEssential\\JqueryMouseWheelAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'all',
        ],
    ],
    'uran1980\\yii\\assets\\jQueryEssential\\JqueryScrollToAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'uran1980\\yii\\assets\\jQueryEssential\\JqueryEasingAsset',
            'all',
        ],
    ],
    'uran1980\\yii\\assets\\jQueryEssential\\JqueryFormAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'all',
        ],
    ],
    'uran1980\\yii\\assets\\jQueryEssential\\JqueryEssentialAsset' => [
        'depends' => [
            'yii\\web\\JqueryAsset',
            'uran1980\\yii\\assets\\jQueryEssential\\JqueryCookieAsset',
            'uran1980\\yii\\assets\\jQueryEssential\\JqueryEasingAsset',
            'uran1980\\yii\\assets\\jQueryEssential\\JqueryMouseWheelAsset',
            'uran1980\\yii\\assets\\jQueryEssential\\JqueryScrollToAsset',
            'uran1980\\yii\\assets\\jQueryEssential\\JqueryFormAsset',
        ],
        'sourcePath' => null,
        'basePath' => null,
        'baseUrl' => null,
        'js' => [],
        'css' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'uran1980\\yii\\assets\\jQueryEssential\\JqueryEssentialAsset',
    ],
    'yii2mod\\alert\\AlertAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'metalguardian\\fotorama\\FotoramaAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'all',
        ],
    ],
    'nodge\\eauth\\assets\\WidgetAssetBundle' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'all',
        ],
    ],
    'nirvana\\infinitescroll\\InfiniteScrollAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'all',
        ],
    ],
    'kartik\\spinner\\SpinnerAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'all',
        ],
    ],
    'yii\\bootstrap\\BootstrapPluginAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'all',
        ],
    ],
    'dosamigos\\multiselect\\MultiSelectAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\bootstrap\\BootstrapPluginAsset',
            'all',
        ],
    ],
    'russ666\\widgets\\CountdownAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'all',
        ],
    ],
    'kartik\\form\\ActiveFormAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\bootstrap\\BootstrapPluginAsset',
            'all',
        ],
    ],
    'yii\\widgets\\ActiveFormAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'all',
        ],
    ],
    'yii\\widgets\\PjaxAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'all',
        ],
    ],
    'frontend\\assets\\AppAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'uran1980\\yii\\assets\\jQueryEssential\\JqueryEssentialAsset',
            'yii2mod\\alert\\AlertAsset',
            'metalguardian\\fotorama\\FotoramaAsset',
            'nodge\\eauth\\assets\\WidgetAssetBundle',
            'nirvana\\infinitescroll\\InfiniteScrollAsset',
            'kartik\\spinner\\SpinnerAsset',
            'dosamigos\\multiselect\\MultiSelectAsset',
            'russ666\\widgets\\CountdownAsset',
            'kartik\\form\\ActiveFormAsset',
            'yii\\widgets\\ActiveFormAsset',
            'yii\\widgets\\PjaxAsset',
            'all',
        ],
    ],
];